#Headless browser option
browser:
  phantomjs: "phantomjs"
  # slimerjs: "slimerjs"

#If you want to have multiple snapping files, set the file name here
snap_file: "lib/wraith/javascript/snap.js"

# Type the name of the directory that shots will be stored in
directory: 'shots'

# Add only 2 domains, key will act as a label
domains:
  english: "http://www.bbc.co.uk/russian"
  russian: "http://www.bbc.co.uk/russian"

#Type screen widths below, here are a couple of examples
screen_widths:
  - 320
  - 600
  - 1280

#Type page URL paths below, here are a couple of examples
paths:
  home: /
  uk_index: /uk

#Amount of fuzz ImageMagick will use
fuzz: '20%'
